
#General Configs
[general]
	GET_STARTER_ITEMS = true
	loot_announcements = true
	require_team_for_dungeons = true
	dont_sync_ambient_mob_data = true
	SCALE_MOB_LEVEL_TO_NEAREST_PLAYER = true
	log_errors = true
	stop_error_spam = true
	STATION_SUCK_NEARBY_CHESTS = false
	#Mobs that are much higher level will hide their levels.
	SKULL_HIDES_LEVEL = true
	#Mns tries to replicate vanilla atk speed and reduces dmg of basic attacks if hit too often
	REMOVE_ATK_SPEED_COOLDOWN = false
	#Mns tries to replicate vanilla bow draw and reduces dmg of basic attacks if bow is not fully drawn. Enable for machine gun bows.
	REMOVE_DRAW_SPEED_COOLDOWN = false
	#Range: > 0
	min_level_map_drops = 25
	#Range: > 0
	MIN_SLIME_SIZE_FOR_LOOT = 3
	#Range: > 0
	DEATH_PENALTY_START_LEVEL = 25
	#Range: > 0
	LEVEL_DISTANCE_PENALTY_LEEWAY = 2
	#Range: 0 ~ 100
	PERC_OFFHAND_WEP_STAT = 25
	#Range: 0.0 ~ 1000.0
	regen_hunger_cost = 10.0
	#Range: 0.0 ~ 1.0
	death_exp_penalty = 0.1
	#Range: 0.0 ~ 1.0
	death_exp_debt = 0.1
	#Range: 0.0 ~ 100.0
	max_death_exp_debt_multi = 1.0
	#Range: 0.0 ~ 1000.0
	exp_gain_multi = 1.0
	#Range: 0.0 ~ 1000.0
	party_radius = 200.0
	#When mobs are this many levels higher than you, a skull will show, indicating danger.
	#Range: 1 ~ 1000
	SHOW_SKULL_ON_MOBS_THAT_ARE_X_LEVELS_HIGHER_THAN_YOU = 5
	#When you are higher or lower level than mobs by X levels, decreases the loot and exp droprate.
	#Range: 0.0 ~ 1.0
	lvl_distance_loot_penalty_per_level = 0.2
	#Range: 0.0 ~ 1.0
	min_loot_chance = 0.2
	#Range: 0.0 ~ 1000.0
	extra_mob_stats_per_lvl = 0.02
	#Range: 0.0 ~ 1000.0
	vanilla_mob_dmg_as_exile_dmg = 1.0
	#Range: 0.0 ~ 10.0
	pvp_dmg_multi = 1.0
	#Range: 0.0 ~ 100000.0
	max_team_distance = 75.0
	#Distance needed from player to despawn mobs in maps, lower means more despawning
	#Range: 5.0 ~ 200.0
	MOB_DESPAWN_DISTANCE_IN_MAPS = 30.0
	#Range: 5.0 ~ 99.0
	MAP_PERCENT_COMPLETE_NEEDED_FOR_BOSS_ARENA = 50.0
	#Range: 0.0 ~ 10.0
	in_combat_regen_multi = 0.5
	#Range: 0.0 ~ 1.0
	COMBAT_TO_PROFESSION_RESTED_XP_GENERATION = 0.25
	#Range: 0.0 ~ 1.0
	PROFESSION_TO_COMBAT_RESTED_XP_GENERATION = 0.1
	#Range: 0.0 ~ 1.0
	RESTED_XP_DEATH_PENALTY = 0.5
	#Additional exp before splitting between players.
	#Range: 0.0 ~ 1.0
	PARTY_EXP_BONUS = 0.20000000298023224
	#Additional drop before splitting between players.
	#Range: 0.0 ~ 1.0
	PARTY_DROP_BONUS = 0.20000000298023224
	#Range: 0.0 ~ 10000.0
	favor_death_loss = 50.0
	#Range: 0 ~ 10000000
	MAX_POSSIBLE_FAVOR = 10000000
	#Range: 0.0 ~ 10000.0
	favor_chest_gain = 1.0
	#Range: 0 ~ 10000000
	MAP_START_COOLDOWN_SECONDS = 120
	#Range: 0.0 ~ 1000.0
	gear_drop_rate = 7.0
	#Range: 0.0 ~ 1000.0
	soul_drop_rate = 0.3
	#Range: 0.0 ~ 1000.0
	gem_drop_rate = 1.0
	#Range: 0.0 ~ 1000.0
	skill_gem_drop_rate = 3.0
	#Range: 0.0 ~ 1000.0
	support_gem_drop_rate = 2.0
	#Range: 0.0 ~ 1000.0
	aura_gem_drop_rate = 2.0
	#Range: 0.0 ~ 1000.0
	rune_drop_rate = 0.5
	#Range: 0.0 ~ 1000.0
	currency_drop_rate = 1.0
	#Range: 0.0 ~ 1000.0
	WATCHER_EYE_DROPRATE = 33.0
	#Range: 0.0 ~ 1000.0
	PROPHECY_COIN_DROPRATE = 1.0
	#Range: 0.0 ~ 1000.0
	jewel_drop_rate = 0.25
	#Range: 0.0 ~ 1000.0
	loot_chest_drop_rate = 0.1
	#Range: 0.0 ~ 1000.0
	OMEN_DROPRATE = 0.1
	#Range: 0.0 ~ 1000.0
	MAP_DROPRATE = 1.0
	#Range: 0.0 ~ 1000.0
	block_cost = 0.25
	#Range: 0 ~ 6
	MAP_GEN_MOB_RADIUS = 1
	#Range: 0 ~ 10
	MAP_GEN_TERRAIN_RADIUS = 4
	#Range: 0 ~ 100
	ITEM_LEVEL_VARIANCE = 3
	#Range: 0 ~ 100
	MOB_LEVEL_VARIANCE = 3
	#Range: 1 ~ 18
	PROPHECY_OFFERS_PER_REROLL = 18
	#Range: 0 ~ 100
	PROPHECY_GEAR_TYPE_CHANCE = 15
	#Range: 0 ~ 100
	PROPHECY_JEWEL_RARITY_CHANCE = 75
	#Range: 0 ~ 100
	PROPHECY_SKILL_GEM_RARITY_CHANCE = 75
	#Range: 0 ~ 100
	PROPHECY_GEAR_RARITY = 75
	#Range: 0 ~ 100
	PROPHECY_SEARCH_RADIUS = 6
	#Range: 0 ~ 1000
	BONUS_EXP_PERCENT_PER_HIGHER_LVL_CHARACTERS = 10
	#Range: 1 ~ 7
	MAX_CHARACTERS = 3
	#Range: 0.0 ~ 100.0
	UNARMED_ENERGY_COST = 10.0
	#This is for modded gear that can't be automatically recognized by the mod. If there's say a weapon like a staff in another mod, but this mod doesn't recognize it. Put it here. The usage is: modid:path:gear_slot_id. Example: minecraft:diamond_sword:sword
	gear_compatibility = ["minecraft:iron_sword:sword"]
	SOUL_CLEANER_ITEM_BLACKLIST = ["minecraft:diamond"]
	#Entities that summons should not attack
	ENTITY_SUMMON_BLACKLIST = ["minecraft:allay", "minecraft:armor_stand"]

	#These are just default values for the Mine and slash Hub > features
	[general."Default Feature Configs"]
		cast_fail_messages = true
		mob_death_messages = false
		exp_chat_messages = false
		damage_messages = false
		profession_exp_messages = false
		auto_pve = false
		aggressive_summons = true
		enable_exp_gain = true
		auto_salvage_drop = false
		stat_order_test = false
		damage_conflict_check = false

